# Default values for sampleapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: chgoutam/mynodejs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.16.1

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 3000
  nodeport: 32000
